---
title: "Practice Activity 4"
author: "Antonio da Silva"
format: 
  html:
    self-contained: true
editor: visual
execute: 
  echo: true
  message: false
  warning: false
---

## **1**

```{r}
library(tidyverse)
library(readxl)

military <- read_xlsx(here::here("Week 4",
                                             "gov_spending_per_capita.xlsx"), 
                                  sheet = "Share of Govt. spending",
                                  skip = 7,
                                  n_max =190)
military
```

2

```{r}
military_clean <- military |> 
  mutate(
    across(everything(),
           .fns = na_if,
           y = ". ."),
    across(everything(), 
          .fns = na_if, 
          y = "xxx")
  )

```

3

```{r}
military_clean <- military_clean |> 
  mutate(across("1988":"2019", as.numeric))
```

4

```{r}
cont_region <- read_xlsx(here::here("Week 4",
                                    "gov_spending_per_capita.xlsx"), 
                      sheet = "Regional totals", 
                      skip = 14) |> 
  filter(Region != "World total (including Iraq)", 
         Region != "World total (excluding Iraq)")
```

5

```{r}
military_clean1 <- military_clean |> 
  anti_join(cont_region, by = c("Country" = "Region")) |> 
  pivot_longer(`1988`:`2019`, names_to = "Year", values_to = "Spending") 
  
```

6

```{r}
military_clean1 |> 
  ggplot(mapping = aes(y = Year, x = Spending)) +
  geom_boxplot()
```
